### ISSUE TITLE
Some Minor Issues

### ISSUE THREAD

**Issue by nitinbaby** [nitinbaby/NSCS-28-Website#6]
Emel,

File: index.html

1. Middle name is not mandatory, remove the validation
2. Add Others in the Gender dropdown
3. email id is not optional make it mandatory
4. Typo in line 111
5.  Input type of phone number should be "tel" (https://www.w3schools.com/tags/att_input_type_tel.asp)
6. Please note that the id of two inputs should not be the same
7. The name of two inputs should not be the same
8. No need to ask for country, we can get the country from PIN
9. line 223, id should not have space, id="One day course" is wrong. it should be id="One_day_course"
10.  line 298. "Fees: Refer to website nscs28.com for more details" this instruction was actually for you 😆 Refer to the website and get the rates for various participants.
11.  Line 349 href refers to a non-existent location. Remove it. If you want to include the bootstrap JS , use the following CDN. 

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

In case you face any issue, call me or post a reply here

regards

**Comment by emelv1327** [comment]
Thank you for your help. I will look into it as per your instructions.

**Comment by emelv1327** [comment]
I thought I have pulled it into my folder.

**Comment by nitinbaby** [comment]
If you want any help, feel free to contact
